#!/bin/bash

set -eu

IP=$1
PORT=$2
HOSTNAME=$3

HOST_ID=$(mkr hosts --name "$HOSTNAME" | jq -r '.[0].id')
(
    leaderboard=$(curl "https://bitnodes.io/api/v1/nodes/leaderboard/${IP}-${PORT}"/ 2>/dev/null)
    timestamp=$(date +%s)
    rank=$(echo "$leaderboard" | jq '.rank')
    echo  -e "bitcoin.bitnodes.rank\t${rank}\t${timestamp}"
    names=(ai bi dli dui hi mli mui ni nsi peer_index pi si vi wli wui)
    for name in "${names[@]}"
    do
      echo  -e "bitcoin.bitnodes_score.${name}\t$(echo "$leaderboard" | jq -r ".${name}")\t${timestamp}"
    done
) | mkr throw --host "$HOST_ID"

