apiVersion: v1
kind: ConfigMap
metadata:
  name: mackerel
data:
  config: |
    plugin:
      metrics:
        prome:
          command:
            - "/bin/sh"
            - "-c"
            - "mackerel-plugin-prometheus-exporter --target http://argocd-application-controller-metrics.argocd.svc.cluster.local:8082/metrics | grep argocd_app_info | sed 's/argocd_app_info-dest_namespace_//g' | sed 's/dest_server_https_kubernetes_default_svc_//g' | sed 's/operation_project_default_repo_https_github_com_dekokun_crypt-manifest_//g' | sed 's/sync_status_//g'"
          timeoutSeconds: 30
