apiVersion: v1
kind: ConfigMap
metadata:
  name: mackerel
data:
  config: |
    plugin:
      metrics:
        bitcoin:
          command:
            - mackerel-plugin-prometheus-exporter
            - --target
            - http://argocd-application-controller-metrics.argocd.svc.cluster.local:8082/metrics
          timeoutSeconds: 30
