apiVersion: apps/v1
kind: Deployment
metadata:
  name: mackerel-deployment
  labels:
    app: mackerel
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mackerel
  template:
    metadata:
      labels:
        app: mackerel
    spec:
      containers:
      - name: mackerel
        image: mackerel/mackerel-container-agent:plugins
        resources:
          requests:
            cpu: 0.004
            memory: 17Mi
          limits:
            memory: 128Mi
        env:
        - name: MACKEREL_KUBERNETES_KUBELET_READ_ONLY_PORT
          value: '0'
        - name: MACKEREL_CONTAINER_PLATFORM
          value: kubernetes
        - name: MACKEREL_HOST_STATUS_ON_START
          value: working
        - name: MACKEREL_AGENT_CONFIG
          value: /etc/mackerel/config
        - name: MACKEREL_KUBERNETES_KUBELET_HOST
          valueFrom:
            fieldRef:
              fieldPath: status.hostIP
        - name: MACKEREL_KUBERNETES_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: MACKEREL_KUBERNETES_POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: MACKEREL_ROLES
          value: bitcoin:argocd
        - name: MACKEREL_APIKEY
          valueFrom:
            secretKeyRef:
              name: mackerel
              key: apikey
        volumeMounts:
          - mountPath: "/etc/mackerel"
            name: mackerel-config
            readOnly: true
        lifecycle:
          postStart:
            exec:
              command:
                - mkr
                - plugin
                - install
                - k1LoW/mackerel-plugin-prometheus-exporter
      volumes:
        - name: mackerel-config
          configMap:
            name: mackerel
            items:
              - key: config
                path: config
