apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: mackerel
  namespace: argocd
spec:
  encryptedData:
    apikey: AgBgZ0GBBml0Ai2ZClxaNBSV5XeKBdXIVy9KjhWZyW3EhymxXt1fbColjcGqFfI6Ex0NZakCj64zAF2CATAg/t0OmROyg5i0fpqyhyCCSOSoPVaUUG7E3W692+ArgWqrv/yyCQu52OukOIpr8XwSw478aR/jc9LVNFd9ZwCaCQLy7PTZGzAKZl3wazOQ3/vGoIYXppb1r986mwFHMDF9iyH68NHhxkInVungZzDufyQKyFVaKohfL8uR8kQ+YG/libTnN++9mb0Tt51MIC0MkDldbMnLsl63iwboyJ+eK8A2kbD6uajXs362HyJU/IIbLgmJjSKaQUKspuIo9FTB4pjd95YcsEo0MRUYA9lSzaAbXmxR0+eZlvSMJXViGoRi7DGiY8WTjNIuTjFIyZ2nDhlctjxiF0V/vp4YF0sCLa4l72nC3rtuIeQjyp1M7jSXFrUFwrz2o5Gakqgo6QC5cLx4N8/pAD7N8MYOxfaKjj9nxaaE6jGa6a4lNHsdnR7/B8oePOkZJwgd6fOJZvuea1/hngiKPAlxU2noshlXjCjsGfLBEmUNg5/dXz9HHmr77FGgr96Wi177OC5RhcDXR274iBtfVwXTR5ahshpuBQQDYMmuqzVhldckyqO9LatZsiqUY8EclPyUpCwxtuseQPkCLYVbdmqITUEsX3tjlsSkjozt7qPH84Om8RU629DCl5/ZI6/DpnWFYtMzK/7ZSflovIkPpgcVTPWvuMbqLWJKzstXSXE1GODOLx2t0g==
    config: AgBu0HcjAnD+PbjKoKuRygPTi53gwOkYKuQIcpQE0pQuWlweOOenOgENvTybKRx0jyAb4kB9JPzFPLvnhb9Fbm3keD7Alg+S12sQ6oAituJ3UXlYMnzW5YoFa+4TaHyByd1KdWiBIEoXh/2vnWw59Avel0kVu2gK9pGyk1ZDQamw7TVPd1vcEI3w9xfDhEEZ6IGz2MBDLdxXXnsOqOclTVMSgLEXyKRRINgPhzQvG38VU2iSmgVgGvNo76gWX54ZceCv6jrEiCeea9E8umArqHHWgkyJk+22405owhuM9RqndCD1XOKrohOq9SmSGZpG+84lfabjyvzF9/xRvqGPYly40Ae//BPrPnEctweJIU0Rq7XqWfShgV/57OEuHBLnl4zghjXMr8wf8AJZJKooLzk4Sf2WI31zwVbkocDOnc2RVP5wN4HwbMdSewjRJpN9ZsaUi19yVDSohYm0H2Sk8Qnf2FZIEZBqO4Oc3wFKB1QeS1wC+r8masObm4MM9vpJ24eup7OUqpzT5DGsbWxRbrAkQH0dClGQ9BxJ8cYmeK1+2+CI5a7HbuhrikLgEvFoiZRYtwnoVWKn1Ct8SAmnWSqknasqeanEVB9VFPmXcXZKYDsVU1/JQE2bKIJtd3JPikgD8eVn0DzGXVP7T0AZDHeZkac5PPmLERPW86L7sHD0duLfLJtjkdEM6O9cBDoOzW5eaaKLGM8e15ca3BJxf/4sKK5axOaFASeB+wRP8zeGGtnD9nt6GoGF4SGogTevyYg7HxaZKTQTuKM54Q8mKeM8o+6s12QzBJM2wacNLsJcF2ste46dJSszDRs227zxsf6VGdP3U91Fob/0ZSzI93g4IXcxTIywbznnp/HApBdN2Zeg9N5TM3bHap+WMlEGnLG1saiv17czGtrnwaXZ9A0Ivhf3dw==
  template:
    data: null
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: mackerel
      namespace: argocd

