apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: mackerel
  namespace: argocd
spec:
  encryptedData:
    apikey: AgBgZ0GBBml0Ai2ZClxaNBSV5XeKBdXIVy9KjhWZyW3EhymxXt1fbColjcGqFfI6Ex0NZakCj64zAF2CATAg/t0OmROyg5i0fpqyhyCCSOSoPVaUUG7E3W692+ArgWqrv/yyCQu52OukOIpr8XwSw478aR/jc9LVNFd9ZwCaCQLy7PTZGzAKZl3wazOQ3/vGoIYXppb1r986mwFHMDF9iyH68NHhxkInVungZzDufyQKyFVaKohfL8uR8kQ+YG/libTnN++9mb0Tt51MIC0MkDldbMnLsl63iwboyJ+eK8A2kbD6uajXs362HyJU/IIbLgmJjSKaQUKspuIo9FTB4pjd95YcsEo0MRUYA9lSzaAbXmxR0+eZlvSMJXViGoRi7DGiY8WTjNIuTjFIyZ2nDhlctjxiF0V/vp4YF0sCLa4l72nC3rtuIeQjyp1M7jSXFrUFwrz2o5Gakqgo6QC5cLx4N8/pAD7N8MYOxfaKjj9nxaaE6jGa6a4lNHsdnR7/B8oePOkZJwgd6fOJZvuea1/hngiKPAlxU2noshlXjCjsGfLBEmUNg5/dXz9HHmr77FGgr96Wi177OC5RhcDXR274iBtfVwXTR5ahshpuBQQDYMmuqzVhldckyqO9LatZsiqUY8EclPyUpCwxtuseQPkCLYVbdmqITUEsX3tjlsSkjozt7qPH84Om8RU629DCl5/ZI6/DpnWFYtMzK/7ZSflovIkPpgcVTPWvuMbqLWJKzstXSXE1GODOLx2t0g==
  template:
    data: null
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: mackerel
      namespace: argocd

