apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: bitcoin
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/dekokun/crypt-manifest.git
    targetRevision: HEAD
    path: bitcoin
  destination:
    server: https://kubernetes.default.svc
    namespace: bitcoin
