apiVersion: v1
kind: Service
metadata:
  name: nlb
  labels:
    app: fullnode
  annotations:
    oci.oraclecloud.com/load-balancer-type: "nlb"
spec:
  type: LoadBalancer
  ports:
  - port: 8333
  selector:
    app: fullnode
