---
apiVersion: v1
kind: Service
metadata:
  name: bitcoin-svc
  labels:
    app: fullnode
spec:
  type: NodePort
  ports:
  - port: 8333
    protocol: "TCP"
    name: "bitcoin-port"
    targetPort: 8333
    nodePort: {{.Values.service.nodePort}}
  selector:
    app: fullnode

