#!/bin/bash

date=$(date +"%Y-%m-%d-%I:%M")
result_file=/tmp/mackerel-plugin-bitoin-${date/%?/}x
if [ ! -e $result_file ]; then
(
  netinfo=$(bitcoin-cli -rpcclienttimeout=30 -rpcuser=dekokun -rpcpassword=JHcXCN5CeBtXceJww9GSZ4kr4TsHoakiYGcv6xrmd5E= -netinfo)
  score=$(echo "$netinfo" | tail -1 | awk '{print $5}')
  height=$(bitcoin-cli -rpcclienttimeout=30 -rpcuser=dekokun -rpcpassword=JHcXCN5CeBtXceJww9GSZ4kr4TsHoakiYGcv6xrmd5E= -getinfo | jq ".blocks")
  in=$(echo "$netinfo" | egrep '^in' | awk '{print $5}')
  out=$(echo "$netinfo" | egrep '^out' | awk '{print $5}')
  block=$(echo "$netinfo" | egrep '^out' | awk '{print $6}')
  total=$(echo "$netinfo" | egrep '^total' | awk '{print $5}')

  leaderboard=$(curl https://bitnodes.io/api/v1/nodes/leaderboard/168.138.219.140-8333/ 2>/dev/null)
  rank=$(echo $leaderboard | jq '.rank')
  echo  -e "bitcoin.net.score\t${score}\t"
  echo  -e "bitcoin.connection.in\t${in}\t"
  echo  -e "bitcoin.connection.out\t${out}\t"
  echo  -e "bitcoin.connection.total\t${total}\t"
  echo  -e "bitcoin.connection.block\t${block}\t"
  echo  -e "bitcoin.block.height\t${height}\t"
  echo  -e "bitcoin.bitnodes.rank\t${rank}\t"


  names=(ai bi dli dui hi mli mui ni nsi peer_index pi si vi wli wui)
  for name in ${names[@]}
  do
    echo  -e "bitcoin.bitnodes_score.${name}\t$(echo $leaderboard | jq -r ".${name}")\t"
  done
) > $result_file
fi
before_date=$(date +"%Y-%m-%d-%I:%M" --date '10 minutes ago')
before_file=/tmp/mackerel-plugin-bitoin-${before_date/%?/}x
rm -f $before_file

timestamp=$(date +%s)
cat $result_file | sed "s/$/${timestamp}/g"

