apiVersion: apps/v1
kind: Deployment
metadata:
  name: bitcoin-fullnode
  labels:
    app: fullnode
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fullnode
  template:
    metadata:
      labels:
        app: fullnode
    spec:
      containers:
      - name: nginx
        image: nginx
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: my-nginx-svc
  labels:
    app: fullnode
spec:
  type: NodePort
  ports:
  - port: 8333
    protocol: "TCP"
    name: "bitcoin-port"
    targetPort: 8333
    nodePort: 30333
  selector:
    app: fullnode
