apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: bitcoin-fullnode
  labels:
    app: fullnode
spec:
  serviceName: "bitcoin-service"
  replicas: 1
  selector:
    matchLabels:
      app: fullnode
  template:
    metadata:
      labels:
        app: fullnode
    spec:
      containers:
      - name: bitcoin-core
        image: ruimarinho/bitcoin-core:22
        args: ["-printtoconsole", "-externalip=bitcoin.dekokun.info", "-dbcache=2000", "-prune=30000"]
        env:
        - name: BITCOIN_DATA
          value: "/var/lib/bitcoin"
        ports:
        - containerPort: 8333
        volumeMounts:
        - name: bitcoinclaim
          mountPath: /var/lib/bitcoin
  volumeClaimTemplates:
  - metadata:
      name: bitcoinclaim
    spec:
      storageClassName: "oci-bv"
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: 50Gi
---
apiVersion: v1
kind: Service
metadata:
  name: bitcoin-svc
  labels:
    app: fullnode
spec:
  type: NodePort
  ports:
  - port: 8333
    protocol: "TCP"
    name: "bitcoin-port"
    targetPort: 8333
    nodePort: 30333
  selector:
    app: fullnode
