installCRDs: false
global:
  image:
    repository:
      alinbalutoiu/argocd
    tag:
      v2.2.2
argo-cd:
  dex:
    enabled: false
  server:
    extraArgs:
      - --insecure
  controller:
    metrics:
      enabled: true
