installCRDs: false
global:
  image:
    repository:
      alinbalutoiu/argocd
    tag:
      v2.2.2
argo-cd:
  dex:
    enabled: false
  server:
    extraArgs:
      - --insecure
  controller:
    metrics:
      enabled: true
    extraContainers:
      - name: mackerel
        image: mackerel/mackerel-container-agent:plugins
        resources:
          requests:
            cpu: 0.004
            memory: 17Mi
          limits:
            memory: 128Mi
        env:
        - name: MACKEREL_KUBERNETES_KUBELET_READ_ONLY_PORT
          value: '0'
        - name: MACKEREL_CONTAINER_PLATFORM
          value: kubernetes
        - name: MACKEREL_HOST_STATUS_ON_START
          value: working
        - name: MACKEREL_AGENT_CONFIG
          value: /etc/mackerel/config
        - name: MACKEREL_KUBERNETES_KUBELET_HOST
          valueFrom:
            fieldRef:
              fieldPath: status.hostIP
        - name: MACKEREL_KUBERNETES_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: MACKEREL_KUBERNETES_POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: MACKEREL_ROLES
          value: bitcoin:full-node
        - name: MACKEREL_APIKEY
          valueFrom:
            secretKeyRef:
              name: mackerel
              key: apikey
        volumeMounts:
          - mountPath: "/etc/mackerel"
            name: mackerel-config
            readOnly: true
        lifecycle:
          postStart:
            exec:
              command:
                - mkr
                - plugin
                - install
                - k1LoW/mackerel-plugin-prometheus-exporter
        terminationGracePeriodSeconds: 60
        volumes:
          - name: mackerel-config
            secret:
              secretName: mackerel
