installCRDs: false
argo-cd:
  sepoServer:
    nodeSelector:
      kubernetes.io/arch: arm64
  dex:
    enabled: false
    nodeSelector:
      kubernetes.io/arch: arm64
  server:
    extraArgs:
      - --insecure
    nodeSelector:
      kubernetes.io/arch: arm64
  controller:
    metrics:
      enabled: true
    nodeSelector:
      kubernetes.io/arch: arm64
  redis:
    nodeSelector:
      kubernetes.io/arch: arm64
  applicationSet:
    image:
      repository: ghcr.io/jr64/argocd-applicationset
      tag: v0.4.0

