name: CI
on:
  push:
jobs:
  lint-helm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Lint Helm
        uses: WyriHaximus/github-action-helm3@v4
        with:
          exec: helm lint ./charts/*
  snapshot-test:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v4
    - name: setup node.js
      uses: actions/setup-node@v4
      with:
        node-version-file: '.node-version'
        cache: npm
    # https://github.com/actions/cache/blob/master/examples.md#node---npm
    - uses: azure/setup-helm@v4
      with:
        version: v3.9.2
    - name: Install Dependencies
      run: npm ci
    - name: test
      run: npm run test
  validate-manifest:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: install kubeconform
      uses: giantswarm/install-binary-action@v2
      with:
        binary: "kubeconform"
        download_url: https://github.com/yannh/${binary}/releases/download/${version}/kubeconform-linux-amd64.tar.gz
        version: "v0.4.12"
        tarball_binary_path: "${binary}"
        smoke_test: "${binary} -h"
    - name: update helm dep
      run: make helm-dep
    - name: test
      run: make validate

